service: auto-remediate

provider:
  name: aws
  runtime: nodejs6.10
  stage: v1
  region: us-east-1
  stackTags:
    service: auto-remediate
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
      Resource:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:logs'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - '*'

    - Effect: Allow
      Action:
        - logs:CreateLogStream
        - logs:PutLogEvents
        - logs:DescribeLogStream
      Resource:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:logs'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'log-group:/aws/lambda/*:*:*'

    - Effect: Allow
      Action: "lambda:InvokeFunction"
      Resource: "*"

    - Effect: Allow
      Action:
        - rds:Describe*
        - rds:ModifyDBInstance
      Resource: "*"

    - Effect: Allow
      Action:
        - s3:GetBucket*
        - s3:PutBucketPolicy
        - s3:PutBucketAcl
        - s3:PutBucketVersioning
      Resource: "*"

    - Effect: Allow
      Action: cloudtrail:UpdateTrail
      Resource: "*"

    - Effect: Allow
      Action:
        - config:Describe*
        - config:Get*
        - config:List*
        - config:Put*
      Resource: "*"

    - Effect: Allow
      Action:
        - sts:GetCallerIdentity
      Resource: "*"

    - Effect: Allow
      Action:
        - iam:AttachRolePolicy
        - iam:CreateRole
        - iam:GetRole
        - iam:PassRole
        - iam:PutRolePolicy
      Resource: "*"

package:
  individually: true
  exclude:
   - "node_modules/**"

functions:

  AutoRemediateOrchestrator:
    handler: functions/AutoRemediateOrchestrator.handler
    timeout: 10
    memorySize: 128
    events:
      - sns:
          topicName: CloudConformity
          displayName: CloudConformity topic
    tags:
      Name: Auto Remediate Orchestrator
      Owner: CloudConformity
      Role: Auto Remediate
      Environment: Ops
    package:
      include:
        - functions/AutoRemediateOrchestrator.js

  AutoRemediateCT-001:
    handler: functions/AutoRemediateCT-001.handler
    memorySize: 128
    tags:
      Name: Auto Remediate CT-001
      Owner: CloudConformity
      Role: Auto Remediate
      Environment: Ops
    package:
      include:
        - functions/AutoRemediateCT-001.js

  AutoRemediateS3-001:
    handler: functions/AutoRemediateS3-001.handler
    memorySize: 128
    tags:
      Name: Auto Remediate S3-001
      Owner: CloudConformity
      Role: Auto Remediate
      Environment: Ops
    package:
      include:
        - functions/AutoRemediateS3-001.js

  AutoRemediateS3-012:
    handler: functions/AutoRemediateS3-012.handler
    memorySize: 128
    tags:
      Name: Auto Remediate S3-012
      Owner: CloudConformity
      Role: Auto Remediate
      Environment: Ops
    package:
      include:
        - functions/AutoRemediateS3-012.js

  AutoRemediateRDS-008:
    handler: functions/AutoRemediateRDS-008.handler
    memorySize: 128
    tags:
      Name: Auto Remediate RDS-008
      Owner: CloudConformity
      Role: Auto Remediate
      Environment: Ops
    package:
      include:
        - functions/AutoRemediateRDS-008.js

  AutoRemediateConfig-001:
    handler: functions/AutoRemediateConfig-001.handler
    timeout: 120
    memorySize: 128
    tags:
      Name: Auto Remediate Config-001
      Owner: CloudConformity
      Role: Auto Remediate
      Environment: Ops
    package:
      include:
        - functions/AutoRemediateConfig-001.js
    role: AutoRemediateConfig001Role

  AutoRemediateCFM-005:
    handler: functions/AutoRemediateCFM-005.handler
    timeout: 120
    memorySize: 128
    tags:
      Name: Auto Remediate CFM-005
      Owner: CloudConformity
      Role: Auto Remediate
      Environment: Ops
    package:
      include:
        - functions/AutoRemediateCFM-005.js
    role: AutoRemediateCFM005Role

  AutoRemediateRS-001:
    handler: functions/AutoRemediateRS-001.handler
    timeout: 120
    memorySize: 128
    tags:
      Name: Auto Remediate RS-001
      Owner: CloudConformity
      Role: Auto Remediate
      Environment: Ops
    package:
      include:
        - functions/AutoRemediateRS-001.js
    role: AutoRemediateRS001Role

  AutoRemediateEC2-002:
    handler: functions/AutoRemediateEC2-002.handler
    timeout: 120
    memorySize: 128
    tags:
      Name: Auto Remediate EC2-002
      Owner: CloudConformity
      Role: Auto Remediate
      Environment: Ops
    package:
      include:
        - functions/AutoRemediateEC2-002.js
    role: AutoRemediateEC2002Role

  AutoRemediateEC2-005:
    handler: functions/AutoRemediateEC2-005.handler
    timeout: 120
    memorySize: 128
    tags:
      Name: Auto Remediate EC2-005
      Owner: CloudConformity
      Role: Auto Remediate
      Environment: Ops
    package:
      include:
        - functions/AutoRemediateEC2-005.js
    role: AutoRemediateEC2005Role

resources:

  Resources:

    AutoRemediateEC2002Role:
      Type: AWS::IAM::Role
      Properties:
        RoleName: AutoRemediateEC2-002Role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: AutoRemediateEC2-002Policy
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - ec2:RevokeSecurityGroupIngress
                  Resource: "*"

    AutoRemediateEC2005Role:
      Type: AWS::IAM::Role
      Properties:
        RoleName: AutoRemediateEC2-005Role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: AutoRemediateEC2-005Policy
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - ec2:RevokeSecurityGroupIngress
                  Resource: "*"

    AutoRemediateRS001Role:
      Type: AWS::IAM::Role
      Properties:
        RoleName: AutoRemediateRS-001Role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: AutoRemediateRS-001Policy
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - redshift:ModifyCluster
                  Resource: "*"

    AutoRemediateCFM005Role:
      Type: AWS::IAM::Role
      Properties:
        RoleName: AutoRemediateCFM-005Role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: AutoRemediateCFM-005Policy
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - cloudformation:UpdateTerminationProtection
                  Resource: "*"

    AutoRemediateConfig001Role:
      Type: AWS::IAM::Role
      Properties:
        RoleName: AutoRemediateConfig-005Role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: AutoRemediateConfig-005Policy
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - config:PutConfigurationRecorder
                    - config:PutDeliveryChannel
                    - config:StartConfigurationRecorder
                  Resource: "*"
